pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm ci
      - yarn build
      - yarn test

  coverage:
    image: robertstettner/drone-codecov
    token: 0732d94b-a52f-4099-b47a-46ffb15c713d
    debug: true
    when:
      branch: master

matrix:
  NODE_VERSION:
    - 6
    - 8
    - latest
